### ISSUE TITLE
No more aud check for different pipelines?

### ISSUE THREAD

**Issue by Dania02525** [bryanjos/plug_jwt#3]
In the new version, I noticed that I could no longer set intended audience in the router with the plug option.  Am I missing it somewhere or is that not part of the new version? BTW, I forked it and added the feature in- if you want to merge it I will probably clean up the way I did it a bit.

**Comment by bryanjos** [comment]
In Joken, I made the recent change to have a Joken.Config behaviour to allow custom addition and validation of claims. That's why the only parameter on the plug is now `config_module`. You can take a look at the README there to get a look at how an implemented one looks. https://github.com/bryanjos/joken

**Comment by Dania02525** [comment]
So to do this now, one would need an additional config file for each aud?

**Comment by bryanjos** [comment]
You shouldn't need an additional config for each one. With the claim and validate_claim functions, you can pattern match on the aud claim and check it from there. Something like this:

```elixir
plug PlugJwt, config_module: My.Config.Module
```

```elixir
  defmodule My.Config.Module do
    @behaviour Joken.Config

    def secret_key(), do: Application.get_env(:app, :secret_key) 

    def algorithm(), do: :HS256

    def encode(map), do: Poison.encode!(map)

    def decode(binary), do: Poison.decode!(binary)

    def claim(:aud, payload) do
      #Return aud here. The payload is payload given to encode
      "some.audience"
    end

    def claim(_, _), do: nil

    def validate_claim(:aud, payload, options) do
      #validate the aud from the payload return either :ok or {:error, message}
    end

    def validate_claim(_, _, _), do: :ok
  end
```

If you prefer to just handle the adding of claims and validation of claims yourself, you can add the claims to your payload before passing it to encode, and validate them yourself when you receive the claims from the connection. To do something like that, you can update the module to look like this:

```elixir
  defmodule My.Config.Module do
    @behaviour Joken.Config

    def secret_key(), do: Application.get_env(:app, :secret_key) 

    def algorithm(), do: :HS256

    def encode(map), do: Poison.encode!(map)

    def decode(binary), do: Poison.decode!(binary)

    def claim(_, _), do: nil

    def validate_claim(_, _, _), do: :ok
  end
```

**Comment by Dania02525** [comment]
Thanks for taking the time to respond.  Sorry to be a bother, but how can I treat different pipelines differently with this? I usually use the aud claim to prevent requests without the aud: claim or without the right aud claim from hitting certain routes.  

In the case above, I can only validate the audience claim against one check.  I can't say, aud: "user" is allowed in this pipeline, aud: "admin" is allowed in this other pipeline.  right?

**Comment by bryanjos** [comment]
No problem and you aren't a bother. It's good to hear about different use cases. I see what you mean now about different pipelines. So I think the change did make that more difficult. Right now the way things are, you would have to probably create a config module for each pipeline just to be on the safe side.

Maybe it does make sense to allow for the adding of claims on the plug. Something like these for your cases

```elixir
plug PlugJwt, config_module: My.Joken.Config, claims: [aud: "user"]
plug PlugJwt, config_module: My.Joken.Config, claims: [aud: "admin"]
```

Where in this case, the claim and validate_claim on the module are the defaults and after decoding, the plug can compare values against the claims in the claims property.

Does that sound like it would help?

**Comment by Dania02525** [comment]
Yeah thats pretty close to what my fork looks like- I just added an extra validate_claim in plug_jwt before claims are returned.  It could probably be cleaned up, if you would like a pr for it I will make it nicer :-) OTOH, maybe I'm the only one using JWT for different access levels, so maybe not worth doing

**Comment by bryanjos** [comment]
Actually I think I have a better idea. What if instead of adding claims, you could give the plug a function that is called after the payload is decoded and validated to determine if the payload is authorized or not? Something like the following:

```elixir
plug PlugJwt, config_module: My.Joken.Config, on_validated_fun: &check_aud/1


def check_aud(payload) do
    Dict.get(payload, "aud") == "admin"
end
```

That could be a better solution. What do you think?

**Comment by Dania02525** [comment]
That could work, I just like the simplicity before of the
```elixir
plug PlugJwt, config_module: My.Joken.Config, aud: "something"
```
where we can just pass it any claims it needs to validate.  The plug module could take the opts after the config module parameter, and use them as a key value pair to ensure validity.  I'll make something up in a gist this weekend

**Comment by bryanjos** [comment]
That may work out well

**Comment by Dania02525** [comment]
How about this: https://gist.github.com/Dania02525/ba018a4106f1b832d3c6
you can optionally enter required claims as claims: [admin: true] to be tested.  I also removed the dependence on Joken.Helpers as its been removed from joken.  I've got a PR with passing tests for it if this looks ok :-)

**Comment by bryanjos** [comment]
Looks good! I think that will work just fine. I will accept the PR when you make it.
